package com.csetutorials.repositories;

import com.csetutorials.models.AutoGeneratedIdRecord;
import org.springframework.data.jpa.repository.JpaRepository;

public interface AutoGeneratedIdRecordRepository extends JpaRepository<AutoGeneratedIdRecord, Long> {

}